export const TOPIC_KEYWORDS = [
    // Location Based
    "spoken-english-classes-in-mumbai",
    "spoken-english-classes-in-delhi",
    "spoken-english-classes-in-bangalore",
    "spoken-english-classes-in-hyderabad",
    "spoken-english-classes-in-pune",
    "spoken-english-classes-in-chennai",
    "spoken-english-classes-in-kolkata",
    "spoken-english-classes-near-me",
    "english-speaking-course-near-me",
    "best-english-speaking-institute",
    "english-coaching-centers-in-ahmedabad",
    "spoken-english-classes-in-jaipur",
    "spoken-english-classes-in-lucknow",
    "spoken-english-classes-in-chandigarh",
    "spoken-english-classes-in-indore",

    // Skill Based
    "how-to-speak-english-fluently",
    "improve-english-pronunciation",
    "learn-corporate-english",
    "business-english-course-online",
    "professional-email-writing-course",
    "english-grammar-for-professionals",
    "advanced-english-vocabulary",
    "hinglish-to-english-translation",
    "english-speaking-practice-app",
    "ai-english-tutor",
    "fluent-english-speaking-course",
    "english-conversation-practice-online",
    "learn-english-speaking-at-home",
    "online-english-speaking-course-free",
    "best-app-to-learn-english-speaking",

    // Interview & Career
    "job-interview-english-preparation",
    "english-for-interview-questions",
    "call-center-english-training",
    "english-for-sales-professionals",
    "english-for-it-professionals",
    "english-for-doctors",
    "english-for-lawyers",
    "resume-writing-english-tips",
    "cover-letter-english-examples",
    "linkedin-bio-english-generator",
    "english-for-mba-students",
    "english-for-engineers",
    "english-for-teachers",
    "english-for-housewives",
    "english-for-government-exams",

    // Specific Pain Points
    "stop-translating-in-head",
    "overcome-fear-of-speaking-english",
    "speak-english-confidently",
    "remove-mother-tongue-influence",
    "fix-indian-accent-english",
    "understand-american-accent",
    "understand-british-accent",
    "write-better-emails-fast",
    "give-presentations-in-english",
    "lead-meetings-in-english",
    "improve-public-speaking-skills",
    "how-to-talk-to-foreign-clients",
    "understand-native-english-speakers",
    "how-to-improve-communication-skills",
    "soft-skills-training-material",

    // Comparisons and "Vs"
    "duolingo-alternative-india",
    "cambly-alternative-india",
    "clappingo-alternative",
    "free-english-speaking-course",
    "online-vs-offline-english-class",
    "ielts-vs-spoken-english",
    "best-online-english-coaching",
    "cheapest-english-speaking-course",
    "free-english-learning-websites",
    "youtube-channels-to-learn-english",

    // Long tail / Niche
    "daily-use-english-sentences",
    "common-english-mistakes-indians-make",
    "learn-english-through-hindi",
    "learn-english-through-tamil",
    "learn-english-through-telugu",
    "learn-english-through-bengali",
    "learn-english-through-marathi",
    "vocabulary-app-for-adults",
    "english-speaking-partner-free",
    "how-to-think-in-english",
    "english-words-daily-use",
    "simple-english-sentences-for-kids",
    "english-story-for-learning",
    "english-grammar-tenses-easy-learning",
    "how-to-learn-english-grammar-step-by-step",
    "english-speaking-topics-for-students",
    "group-discussion-topics-with-answers",
    "debate-topics-for-students",
    "speech-topics-for-students",
    "tongue-twisters-in-english"
];
